name: Assign labels
on:
  repository_dispatch:
    types: [assign-labels-command]

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      #      - name: Assign labels
      #        uses: actions/github-script@0.4.0
      #          with:
      #            github-token: ${{secrets.GITHUB_BOT_TOKEN}}
      #            script: |
      #              github.issues.addLabels({
      #                issue_number: context.issue.number,
      #                owner: context.repo.owner,
      #                repo: ${{ github.event.client_payload.pull_request.head.repo.full_name }},
      #                labels: ['Triage']
      #              })

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
