name: Greet contributor
on:
  repository_dispatch:
    types: [greet-contributor-command]

jobs:
  greet-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Greet contributor
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_BOT_TOKEN}}
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination

            console.log('Executing Greet contributor script');

            const creator = 'aknyshtest';
            const issueNumber = 16;
            const owner = 'cloudposse';
            const repo = 'actions';
            let firstTimeContributor = true;
            let message = '';

            const opts = github.issues.listForRepo.endpoint.merge({
              owner: owner,
              repo: repo,
              creator: creator,
              state: 'all'
            });

            const issues = await github.paginate(opts);

            for (const issue of issues) {
              if (issue.number === issueNumber) {
                continue;
              }

              if (issue.pull_request) {
                firstTimeContributor = false;
                break;
              }
            }

            if (firstTimeContributor) {
              console.log('PR creator is a first time contributor');

              message = `
              Welcome @${creator}

              Thank you for submitting this PR! If you haven't already [joined our slack community](https://slack.sweetops.com), then we invite you to do so.

              We receive an overwhelming number of contributions. By joining our slack, we'll be able to review your PR faster.

              [![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)
              `;
            }
            else {
              console.log('PR creator is already a contributor');

              message = `
              @${creator} thanks again for your contribution!

              We will review this PR shortly.
              `;
            }

            await github.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: message
            });

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
